services:
  elasticsearch:
    image: elasticsearch:8.14.3
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - 9200:9200
    volumes:
      - ./configs/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  kibana:
    image: kibana:8.14.3
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200 

  logstash:
    image: logstash:8.14.3
    environment:
      XPACK_MONITORING_ENABLED: "false"
      ES_HOST: "elasticsearch:9200"
    ports:
      - "5044:5044/udp"
    volumes:
      - ./configs/logstash/pipelines.yml:/usr/share/logstash/config/pipelines.yml
      - ./configs/logstash/pipelines:/usr/share/logstash/config/pipelines
      - ./logs:/var/log/nginx
    depends_on:
          - elasticsearch
    
  filebeat:
    image: elastic/filebeat:8.14.3
    volumes:
      - ./logs:/var/log/app/
      - ./configs/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
    depends_on:
      - logstash
      - elasticsearch
      - kibana

  nginx:
    image: nginx:stable-alpine3.21-perl
    ports:
      - "80:80"
    volumes:
      - ./logs:/var/log/nginx